apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sessions.gorilla.michaelvenezia.com
spec:
  group: gorilla.michaelvenezia.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                data:
                  type: string
            status:
              type: object
              properties:
                ttl:
                  type: string
  names:
    kind: Session
    plural: sessions
  scope: Namespaced
