/*
Some boilerplate
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// SessionListerExpansion allows custom methods to be added to
// SessionLister.
type SessionListerExpansion interface{}

// SessionNamespaceListerExpansion allows custom methods to be added to
// SessionNamespaceLister.
type SessionNamespaceListerExpansion interface{}
