/*
Some boilerplate
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	sessionv1alpha1 "github.com/venezia/k8s-gorilla-session-store/k8s/api/session/v1alpha1"
	versioned "github.com/venezia/k8s-gorilla-session-store/k8s/client/clientset/versioned"
	internalinterfaces "github.com/venezia/k8s-gorilla-session-store/k8s/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/venezia/k8s-gorilla-session-store/k8s/client/listers/session/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// SessionInformer provides access to a shared informer and lister for
// Sessions.
type SessionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.SessionLister
}

type sessionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewSessionInformer constructs a new informer for Session type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewSessionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredSessionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredSessionInformer constructs a new informer for Session type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredSessionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GorillaV1alpha1().Sessions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.GorillaV1alpha1().Sessions(namespace).Watch(context.TODO(), options)
			},
		},
		&sessionv1alpha1.Session{},
		resyncPeriod,
		indexers,
	)
}

func (f *sessionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredSessionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *sessionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sessionv1alpha1.Session{}, f.defaultInformer)
}

func (f *sessionInformer) Lister() v1alpha1.SessionLister {
	return v1alpha1.NewSessionLister(f.Informer().GetIndexer())
}
