/*
Some boilerplate
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/venezia/k8s-gorilla-session-store/k8s/client/clientset/versioned/typed/session/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeGorillaV1alpha1 struct {
	*testing.Fake
}

func (c *FakeGorillaV1alpha1) Sessions(namespace string) v1alpha1.SessionInterface {
	return &FakeSessions{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeGorillaV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
