/*
Some boilerplate
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/venezia/k8s-gorilla-session-store/k8s/api/session/v1alpha1"
	sessionv1alpha1 "github.com/venezia/k8s-gorilla-session-store/k8s/client/applyconfiguration/session/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSessions implements SessionInterface
type FakeSessions struct {
	Fake *FakeGorillaV1alpha1
	ns   string
}

var sessionsResource = v1alpha1.SchemeGroupVersion.WithResource("sessions")

var sessionsKind = v1alpha1.SchemeGroupVersion.WithKind("Session")

// Get takes name of the session, and returns the corresponding session object, and an error if there is any.
func (c *FakeSessions) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Session, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(sessionsResource, c.ns, name), &v1alpha1.Session{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Session), err
}

// List takes label and field selectors, and returns the list of Sessions that match those selectors.
func (c *FakeSessions) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.SessionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(sessionsResource, sessionsKind, c.ns, opts), &v1alpha1.SessionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.SessionList{ListMeta: obj.(*v1alpha1.SessionList).ListMeta}
	for _, item := range obj.(*v1alpha1.SessionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested sessions.
func (c *FakeSessions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(sessionsResource, c.ns, opts))

}

// Create takes the representation of a session and creates it.  Returns the server's representation of the session, and an error, if there is any.
func (c *FakeSessions) Create(ctx context.Context, session *v1alpha1.Session, opts v1.CreateOptions) (result *v1alpha1.Session, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(sessionsResource, c.ns, session), &v1alpha1.Session{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Session), err
}

// Update takes the representation of a session and updates it. Returns the server's representation of the session, and an error, if there is any.
func (c *FakeSessions) Update(ctx context.Context, session *v1alpha1.Session, opts v1.UpdateOptions) (result *v1alpha1.Session, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(sessionsResource, c.ns, session), &v1alpha1.Session{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Session), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSessions) UpdateStatus(ctx context.Context, session *v1alpha1.Session, opts v1.UpdateOptions) (*v1alpha1.Session, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(sessionsResource, "status", c.ns, session), &v1alpha1.Session{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Session), err
}

// Delete takes name of the session and deletes it. Returns an error if one occurs.
func (c *FakeSessions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(sessionsResource, c.ns, name, opts), &v1alpha1.Session{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSessions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(sessionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.SessionList{})
	return err
}

// Patch applies the patch and returns the patched session.
func (c *FakeSessions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Session, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sessionsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Session{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Session), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied session.
func (c *FakeSessions) Apply(ctx context.Context, session *sessionv1alpha1.SessionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Session, err error) {
	if session == nil {
		return nil, fmt.Errorf("session provided to Apply must not be nil")
	}
	data, err := json.Marshal(session)
	if err != nil {
		return nil, err
	}
	name := session.Name
	if name == nil {
		return nil, fmt.Errorf("session.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sessionsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.Session{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Session), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeSessions) ApplyStatus(ctx context.Context, session *sessionv1alpha1.SessionApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Session, err error) {
	if session == nil {
		return nil, fmt.Errorf("session provided to Apply must not be nil")
	}
	data, err := json.Marshal(session)
	if err != nil {
		return nil, err
	}
	name := session.Name
	if name == nil {
		return nil, fmt.Errorf("session.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(sessionsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.Session{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Session), err
}
